project:
  type: website
  output-dir: docs

website:
  title: "The Data Mage"
  navbar:
    left:
      - text: "Set Analysis"
        href: /notebooks/10-eda/02-draft-data/01-premier-play/00-intro.html
      # - text: "Home" #see docs/index.html for the redirect to the home page.
      #   href: /notebooks/00-intro/00-00-table-of-contents.html
      - text: "About"
        href: /notebooks/00-intro/10-introduction.html
    right:
      - icon: github
        href: https://github.com/meehljd/mtg-modeling
      # - icon: blog
      #   href: blog.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/meehl/

format:
  html:
    theme: flatly
    toc: true
    toc-depth: 2
    # css: styles.css
    include-after-body: _includes/_footer.html
    analytics: 
      google: G-W1YKM7R5E6
      
number-sections: true

# LANGUAGE & CODE EXECUTION
execute:
  enabled: false
  echo: false
  warning: false
  error: false
  freeze: auto
jupyter: python3

# PAGE LAYOUT
link-citations: true
code-fold: true
share: true
